name: gladbettor
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build    number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8+12

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.0
  firebase_database: ^3.1.5
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.0.6
  path:
  http:
  intl:
  path_drawing:
  smooth_page_indicator: ^0.1.5
  draggable_scrollbar: ^0.0.4
  page_view_indicators: ^1.3.1
  connectivity: ^0.4.8+6
  image_picker: ^0.6.5
  flutter_svg: ^0.18.1
  flutter_offline: ^0.3.0
  shared_preferences: ^0.5.7+3
  rxdart: ^0.23.1
  url_launcher: ^5.5.0
  collection: ^1.14.12
  in_app_purchase: ^0.3.4+16
  country_pickers: ^1.3.0
  searchable_dropdown: ^1.1.3
  dropdown_search: ^0.4.4
  dio: ^3.0.1
  firebase_messaging: ^6.0.16
  flutter_local_notifications: ^1.4.4+2
  intro_slider:
    path: flutter-intro-slider
  flutter_html: ^1.0.0 #Html Text dependencies
  flutter_windowmanager: ^0.0.2
  firebase_analytics: ^5.0.16
  flutter_inapp_purchase: ^2.2.0
  firebase_admob: ^0.9.3+4
  dots_indicator: ^1.2.0
  admob_consent: ^1.1.0
  flutter_staggered_grid_view: ^0.3.0
  in_app_update: ^1.1.14
  package_info: ^0.4.3+2
  device_info: ^1.0.0
  delayed_display: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.8.0

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Images/
    - assets/Images/sticker_1.svg
    - assets/Images/sticker_2.svg
    - assets/Images/sticker_3.svg
    - assets/Images/sticker_4.svg
    - assets/Images/sticker_5.svg
    - assets/Images/sticker_6.svg
#    - assets/Images/box_1.png
    - assets/Images/box_2.png
    - assets/Images/box_3.png
    - assets/Images/box_4.png
    - assets/Images/box_5.png
    - assets/Images/box_6.png
    - assets/Images/profile_1.png
    - assets/Images/profile_2.png
    - assets/Images/icon/
    - assets/flag/
    - assets/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans.ttf

    - family: RalewayBold
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf

    - family: RalewayMedium
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf

    - family: RalewaySemiBold
      fonts:
        - asset: assets/fonts/Raleway-SemiBold.ttf

    - family: OpenSansBold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf

    - family: OpenSansRegular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf

    - family: OpenSansSemiBold
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
